services:
  back:
    build:
      context: ./back
    environment:
      - ALLOWED_ORIGINS=*
    ports:
      - "8000:8000"

  front:
    build:
      context: ./front
    depends_on:
      - back
    ports:
      - "3000:80"
