services:
  back:
    build:
      context: /home/runner/work/home-credit-risk-app/home-credit-risk-app/back
    ports:
      - "8000:8000"

  front:
    build:
      context: /home/runner/work/home-credit-risk-app/home-credit-risk-app/front
    depends_on:
      - back
    ports:
      - "3000:80"
